[package]
name = "Sophia"
version = "0.1.0"
edition = "2021"
authors = ["Rogerio Ara√∫jo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/sophia"
homepage = "https://github.com/ararog/sophia"
description = "Very Tiny Server"
readme = "README.md"
license = "MIT"
keywords = ["framework", "backend", "rest-server", "rest"]
publish = true
rust-version = "1.64.0"

[dependencies]
bytes = "1.11.0"
clap = { version = "4.5.54", features = ["derive"] }
http = "1.4.0"
http-body-util = "0.1.3"
hyper-util = "0.1.19"
log = "0.4.29"
thiserror = "2.0.18"
vetis = "0.1.1"
