[package]
name = "jsonmock"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
env_logger = "0.11.8"
http-body-util = "0.1.3"
hyper = "1.8.1"
sofie = { version = "0.0.3", path = "../.." }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
