[package]
name = "jsonmock"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
http-body-util = "0.1.3"
hyper = "1.8.1"
Sophia = { version = "0.1.0", path = "../.." }
std-logger = "0.5.7"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
